MAKE 	:=	make -f
WIN		:=	Makefile.windows
LNX		:=	Makefile.linux

win:
	$(MAKE) $(WIN)

win_fclean:
	$(MAKE) $(WIN) fclean

win_re:
	$(MAKE) $(WIN) re

win_clean:
	$(MAKE) $(WIN) clean

lnx:
	$(MAKE) $(LNX)

lnx_fclean:
	$(MAKE) $(LNX) fclean

lnx_clean:
	$(MAKE) $(LNX) clean

lnx_re:
	$(MAKE) $(LNX) re
